# Generated by Django 5.1.4 on 2024-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_category_alter_event_organizer'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='tags.tag'),
        ),
    ]
